//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagement
{
    using System;
    using System.Collections.Generic;

    public partial class IssuanceOrderItem
    {
        public int IssuanceOrderID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }

        public virtual IssuanceOrder IssuanceOrder { get; set; }
        public virtual Item Item { get; set; }

    }
}
