//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSupplier
    {
        public int ItemSupplierID { get; set; }
        public int ItemID { get; set; }
        public int SupplierID { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
